"use client";

import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles, ChevronRight, ChevronLeft, MapPin, DollarSign,
  Users, Calendar, Loader, Copy, Download, Check, FileText,
  RefreshCw, Plane,
} from "lucide-react";
import ReactMarkdown from "react-markdown";

const travelTypes = ["Adventure", "Relaxation", "Cultural", "Family", "Solo", "Luxury"];
const seasons = ["Spring", "Summer", "Fall", "Winter", "Any"];
const interests = ["History", "Nature", "Food", "Adventure", "Culture", "Shopping", "Nightlife", "Wellness"];

const CURRENCIES = [
  { code: "USD", symbol: "$", label: "USD — US Dollar", rate: 1 },
  { code: "BDT", symbol: "৳", label: "BDT — Bangladeshi Taka", rate: 110 },
  { code: "EUR", symbol: "€", label: "EUR — Euro", rate: 0.92 },
  { code: "GBP", symbol: "£", label: "GBP — British Pound", rate: 0.79 },
  { code: "INR", symbol: "₹", label: "INR — Indian Rupee", rate: 83 },
];

interface PlannerState {
  destination: string;
  budget: string;
  travelType: string;
  season: string;
  selectedInterests: string[];
  days: string;
}

interface Results {
  recommendations?: string;
  itinerary?: string;
  budget?: string;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";

// ─── PDF Generator ────────────────────────────────────────────────────────────
function generatePDF(formData: PlannerState, results: Results) {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>TravelAI Trip Plan — ${formData.destination}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #0a0a14; color: #e2e8f0; padding: 40px; }
    .header { background: linear-gradient(135deg, #4f46e5, #06b6d4); border-radius: 16px; padding: 32px; margin-bottom: 32px; }
    .header h1 { font-size: 28px; font-weight: 800; color: white; margin-bottom: 8px; }
    .header p { color: rgba(255,255,255,0.8); font-size: 14px; }
    .meta { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 20px; }
    .meta-item { background: rgba(255,255,255,0.15); border-radius: 8px; padding: 8px 14px; font-size: 13px; color: white; }
    .section { background: #111827; border: 1px solid #1f2937; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
    .section-title { font-size: 18px; font-weight: 700; color: #818cf8; margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }
    .section-title::before { content: ""; display: inline-block; width: 4px; height: 20px; background: linear-gradient(#4f46e5, #06b6d4); border-radius: 2px; }
    .content { font-size: 14px; line-height: 1.8; color: #cbd5e1; white-space: pre-wrap; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1f2937; color: #475569; font-size: 12px; }
    .badge { display: inline-block; background: #4f46e5; color: white; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; }
    @media print { body { background: white; color: #1e293b; } .section { background: #f8fafc; border-color: #e2e8f0; } .content { color: #334155; } }
  </style>
</head>
<body>
  <div class="header">
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:16px">
      <div style="background:rgba(255,255,255,0.2);padding:10px;border-radius:12px;font-size:24px">✈</div>
      <div>
        <div style="font-size:12px;color:rgba(255,255,255,0.7);text-transform:uppercase;letter-spacing:0.1em">TravelAI — AI Trip Plan</div>
        <h1>${formData.destination}</h1>
      </div>
    </div>
    <div class="meta">
      <div class="meta-item">📅 ${formData.days} Days</div>
      <div class="meta-item">💰 ${formData.budget}</div>
      <div class="meta-item">🧳 ${formData.travelType}</div>
      <div class="meta-item">🌤 ${formData.season}</div>
      <div class="meta-item">❤️ ${formData.selectedInterests.join(", ")}</div>
    </div>
    <div style="margin-top:16px;font-size:12px;color:rgba(255,255,255,0.6)">Generated on ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</div>
  </div>

  ${results.recommendations ? `
  <div class="section">
    <div class="section-title">🌍 AI Destination Recommendations</div>
    <div class="content">${results.recommendations}</div>
  </div>` : ""}

  ${results.itinerary ? `
  <div class="section">
    <div class="section-title">📅 Day-by-Day Itinerary</div>
    <div class="content">${results.itinerary}</div>
  </div>` : ""}

  ${results.budget ? `
  <div class="section">
    <div class="section-title">💰 Budget Breakdown</div>
    <div class="content">${results.budget}</div>
  </div>` : ""}

  <div class="footer">
    <p>Generated by <strong>TravelAI</strong> — AI-Powered Travel Planning Platform</p>
    <p style="margin-top:4px">hello@travelai.com · travelai.com</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `TravelAI-Plan-${formData.destination.replace(/[^a-z0-9]/gi, "-")}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function AIPlannerPage() {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<Results>({});
  const [showResults, setShowResults] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const [currency, setCurrency] = useState(CURRENCIES[0]);

  const [formData, setFormData] = useState<PlannerState>({
    destination: "",
    budget: "",
    travelType: "",
    season: "",
    selectedInterests: [],
    days: "",
  });

  const handleInterestToggle = (interest: string) => {
    setFormData((prev) => ({
      ...prev,
      selectedInterests: prev.selectedInterests.includes(interest)
        ? prev.selectedInterests.filter((i) => i !== interest)
        : [...prev.selectedInterests, interest],
    }));
  };

  const isStepValid = () => {
    switch (step) {
      case 1: return formData.destination.trim() !== "";
      case 2: return formData.budget !== "";
      case 3: return formData.travelType !== "";
      case 4: return formData.season !== "";
      case 5: return formData.selectedInterests.length > 0;
      case 6: return formData.days !== "";
      default: return false;
    }
  };

  const copySection = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(null), 2000);
  };

  // Convert dollar amounts in text to selected currency
  const convertCurrency = (text: string): string => {
    if (currency.rate === 1) return text;
    return text.replace(/\$\s?([\d,]+(?:\.\d{1,2})?)/g, (_, num) => {
      const usd = parseFloat(num.replace(/,/g, ""));
      const converted = Math.round(usd * currency.rate);
      return `${currency.symbol}${converted.toLocaleString()}`;
    });
  };

  const generatePlan = async () => {
    setLoading(true);
    try {
      // Sequential calls — better error handling than Promise.all
      let recommendations = "";
      let itinerary = "";
      let budget = "";

      try {
        const recRes = await fetch(`${API_BASE}/api/ai/recommendations`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            budget: formData.budget,
            travelType: formData.travelType,
            season: formData.season,
            locationPreference: formData.destination,
          }),
        });
        if (recRes.ok) {
          const rec = await recRes.json();
          recommendations = rec.result || "";
        }
      } catch { /* continue */ }

      try {
        const itRes = await fetch(`${API_BASE}/api/ai/itinerary`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            destination: formData.destination,
            days: formData.days,
            interests: formData.selectedInterests.join(", "),
          }),
        });
        if (itRes.ok) {
          const it = await itRes.json();
          itinerary = it.result || "";
        }
      } catch { /* continue */ }

      try {
        const budRes = await fetch(`${API_BASE}/api/ai/budget`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            destination: formData.destination,
            days: formData.days,
            travelStyle: formData.travelType,
          }),
        });
        if (budRes.ok) {
          const bud = await budRes.json();
          budget = bud.result || "";
        }
      } catch { /* continue */ }

      if (!recommendations && !itinerary && !budget) {
        alert("Could not connect to AI backend. Make sure the backend is running on port 5000 and GEMINI_API_KEY is set.");
        return;
      }

      setResults({ recommendations, itinerary, budget });
      setShowResults(true);
    } catch (error) {
      alert("Failed to generate travel plan. Please check the backend is running.");
    } finally {
      setLoading(false);
    }
  };

  const stepLabels = ["Destination", "Budget", "Travel Style", "Season", "Interests", "Duration"];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      {/* Hero */}
      <div className="relative overflow-hidden bg-[radial-gradient(ellipse_at_top,rgba(79,70,229,0.2),transparent_50%)] px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <div className="inline-flex items-center gap-2 rounded-full bg-brand-600/20 px-4 py-2 text-sm font-semibold text-brand-300 border border-brand-500/30 mb-6">
              <Sparkles size={16} />
              AI-Powered Travel Planning
            </div>
            <h1 className="mt-4 text-5xl font-bold tracking-tight text-white sm:text-6xl">
              Your Personal{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-400 to-cyan-400">
                Trip Planner
              </span>
            </h1>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-300">
              Answer 6 quick questions and get a full AI-generated itinerary, budget breakdown, and destination recommendations — instantly.
            </p>
          </motion.div>
        </div>
      </div>

      <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        {!showResults ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="grid gap-8 lg:grid-cols-[280px_1fr]">
            {/* Sidebar */}
            <aside className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5 h-fit sticky top-24">
              <h3 className="text-sm font-semibold text-white mb-5 uppercase tracking-wider">Plan Your Trip</h3>
              <div className="space-y-2">
                {stepLabels.map((label, i) => {
                  const s = i + 1;
                  const isActive = step === s;
                  const isDone = step > s;
                  return (
                    <button
                      key={s}
                      onClick={() => setStep(s)}
                      className={`w-full flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium transition-all ${
                        isActive ? "border border-brand-500 bg-brand-600/20 text-brand-200"
                        : isDone ? "border border-green-500/30 bg-green-500/10 text-green-300"
                        : "border border-slate-700 bg-slate-950/80 text-slate-400 hover:border-slate-600"
                      }`}
                    >
                      <span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold shrink-0 ${
                        isActive ? "bg-brand-600 text-white"
                        : isDone ? "bg-green-500 text-white"
                        : "bg-slate-800 text-slate-400"
                      }`}>
                        {isDone ? "✓" : s}
                      </span>
                      {label}
                    </button>
                  );
                })}
              </div>

              {/* Progress */}
              <div className="mt-5">
                <div className="flex justify-between text-xs text-slate-500 mb-1.5">
                  <span>Progress</span>
                  <span>{Math.round(((step - 1) / 6) * 100)}%</span>
                </div>
                <div className="h-1.5 bg-slate-800 rounded-full overflow-hidden">
                  <motion.div
                    animate={{ width: `${((step - 1) / 6) * 100}%` }}
                    className="h-full bg-gradient-to-r from-brand-600 to-cyan-500 rounded-full"
                  />
                </div>
              </div>

              <button
                onClick={generatePlan}
                disabled={!formData.destination || !formData.budget || !formData.travelType || !formData.season || formData.selectedInterests.length === 0 || !formData.days || loading}
                className="mt-5 w-full rounded-xl bg-gradient-to-r from-brand-600 to-brand-700 hover:from-brand-500 hover:to-brand-600 px-4 py-3 text-sm font-semibold text-white transition-all disabled:opacity-40 disabled:cursor-not-allowed shadow-lg shadow-brand-600/20"
              >
                {loading ? (
                  <span className="flex items-center justify-center gap-2"><Loader className="animate-spin" size={15} /> Generating...</span>
                ) : (
                  <span className="flex items-center justify-center gap-2"><Sparkles size={15} /> Generate Plan</span>
                )}
              </button>
            </aside>

            {/* Form */}
            <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
              <AnimatePresence mode="wait">
                {step === 1 && (
                  <motion.div key="s1" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    <div>
                      <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">Where would you like to go?</label>
                      <input
                        type="text"
                        value={formData.destination}
                        onChange={(e) => setFormData({ ...formData, destination: e.target.value })}
                        placeholder="e.g. Paris, Thailand, Japan..."
                        className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3.5 text-white placeholder-slate-500 focus:border-brand-500 focus:outline-none transition-colors"
                      />
                    </div>
                    <div className="rounded-xl bg-brand-500/5 border border-brand-500/20 p-4 text-sm text-slate-400">
                      💡 Be specific! "Bali in Summer" gives better results than just "Bali"
                    </div>
                  </motion.div>
                )}

                {step === 2 && (
                  <motion.div key="s2" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                    <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">What's your budget?</label>
                    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                      {["$500–1,000", "$1,000–2,500", "$2,500–5,000", "$5,000–10,000", "$10,000+", "Flexible"].map((b) => (
                        <button key={b} onClick={() => setFormData({ ...formData, budget: b })}
                          className={`rounded-xl px-4 py-3.5 text-sm font-medium transition-all ${formData.budget === b ? "border border-brand-500 bg-brand-600/20 text-brand-200" : "border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-600"}`}>
                          {b}
                        </button>
                      ))}
                    </div>
                  </motion.div>
                )}

                {step === 3 && (
                  <motion.div key="s3" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                    <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">What's your travel style?</label>
                    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                      {travelTypes.map((t) => (
                        <button key={t} onClick={() => setFormData({ ...formData, travelType: t })}
                          className={`rounded-xl px-4 py-3.5 text-sm font-medium transition-all ${formData.travelType === t ? "border border-brand-500 bg-brand-600/20 text-brand-200" : "border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-600"}`}>
                          {t}
                        </button>
                      ))}
                    </div>
                  </motion.div>
                )}

                {step === 4 && (
                  <motion.div key="s4" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                    <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">When do you want to travel?</label>
                    <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
                      {seasons.map((s) => (
                        <button key={s} onClick={() => setFormData({ ...formData, season: s })}
                          className={`rounded-xl px-4 py-3.5 text-sm font-medium transition-all ${formData.season === s ? "border border-brand-500 bg-brand-600/20 text-brand-200" : "border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-600"}`}>
                          {s}
                        </button>
                      ))}
                    </div>
                  </motion.div>
                )}

                {step === 5 && (
                  <motion.div key="s5" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                    <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">What are you interested in? (Select at least 1)</label>
                    <div className="flex flex-wrap gap-2.5">
                      {interests.map((i) => (
                        <button key={i} onClick={() => handleInterestToggle(i)}
                          className={`rounded-full px-4 py-2 text-sm font-medium transition-all ${formData.selectedInterests.includes(i) ? "border border-brand-500 bg-brand-600/20 text-brand-200" : "border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-600"}`}>
                          {i}
                        </button>
                      ))}
                    </div>
                    <p className="text-sm text-slate-500">{formData.selectedInterests.length} selected</p>
                  </motion.div>
                )}

                {step === 6 && (
                  <motion.div key="s6" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    <label className="text-sm uppercase tracking-widest text-slate-400 mb-3 block">How many days?</label>
                    <input
                      type="number" min="1" max="365"
                      value={formData.days}
                      onChange={(e) => setFormData({ ...formData, days: e.target.value })}
                      placeholder="e.g. 7, 10, 14..."
                      className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3.5 text-white placeholder-slate-500 focus:border-brand-500 focus:outline-none transition-colors"
                    />
                    {formData.days && (
                      <p className="text-slate-400 text-sm">
                        A {formData.days}-day trip to {formData.destination || "your destination"} — sounds amazing!
                      </p>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Navigation */}
              <div className="mt-8 flex gap-3">
                <button onClick={() => setStep(Math.max(1, step - 1))} disabled={step === 1}
                  className="inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-5 py-3 text-sm font-semibold text-slate-300 transition-all disabled:opacity-40 hover:border-slate-600">
                  <ChevronLeft size={16} /> Back
                </button>
                <button onClick={() => setStep(Math.min(6, step + 1))} disabled={!isStepValid() || step === 6}
                  className="ml-auto inline-flex items-center gap-2 rounded-xl bg-brand-600 hover:bg-brand-500 px-5 py-3 text-sm font-semibold text-white transition-all disabled:opacity-40">
                  Next <ChevronRight size={16} />
                </button>
              </div>
            </div>
          </motion.div>
        ) : (
          // Results
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
              <div>
                <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                  <Plane size={22} className="text-brand-400 -rotate-45" />
                  Your Trip Plan is Ready!
                </h2>
                <p className="mt-1 text-slate-400 text-sm">
                  {formData.days} days in <span className="text-white font-medium">{formData.destination}</span> · {formData.budget} · {formData.travelType}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => generatePDF(formData, results)}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 shadow-lg shadow-amber-500/20 transition-all"
                >
                  <Download size={16} />
                  Download PDF
                </button>
                <button
                  onClick={() => { setShowResults(false); setStep(1); setResults({}); }}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold border border-slate-700 text-slate-300 hover:border-slate-600 hover:text-white transition-all"
                >
                  <RefreshCw size={15} />
                  New Plan
                </button>
              </div>
            </div>

            {/* Currency Selector */}
            <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900/50 px-5 py-4">
              <DollarSign size={16} className="text-amber-400 shrink-0" />
              <span className="text-sm text-slate-300 font-medium">Display currency:</span>
              <select
                value={currency.code}
                onChange={(e) => {
                  const found = CURRENCIES.find((c) => c.code === e.target.value);
                  if (found) setCurrency(found);
                }}
                className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:border-brand-500 focus:outline-none transition-colors"
              >
                {CURRENCIES.map((c) => (
                  <option key={c.code} value={c.code}>{c.label}</option>
                ))}
              </select>
              {currency.rate !== 1 && (
                <span className="text-xs text-slate-500">
                  1 USD = {currency.rate} {currency.code}
                </span>
              )}
            </div>

            {/* Trip summary pills */}
            <div className="flex flex-wrap gap-2">
              {[
                { icon: "📍", label: formData.destination },
                { icon: "📅", label: `${formData.days} days` },
                { icon: "💰", label: formData.budget },
                { icon: "🧳", label: formData.travelType },
                { icon: "🌤", label: formData.season },
                ...formData.selectedInterests.map((i) => ({ icon: "❤️", label: i })),
              ].map((pill, i) => (
                <span key={i} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-slate-800 border border-slate-700 text-slate-300 text-xs font-medium">
                  {pill.icon} {pill.label}
                </span>
              ))}
            </div>

            {/* Result sections */}
            {[
              { key: "recommendations", title: "AI Destination Recommendations", icon: <MapPin size={20} className="text-brand-400" />, content: results.recommendations },
              { key: "itinerary", title: "Day-by-Day Itinerary", icon: <Calendar size={20} className="text-cyan-400" />, content: results.itinerary },
              { key: "budget", title: "Budget Breakdown", icon: <DollarSign size={20} className="text-amber-400" />, content: results.budget },
            ].map(({ key, title, icon, content }) => content ? (
              <motion.div key={key} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }}
                className="rounded-2xl border border-slate-800 bg-slate-900/50 overflow-hidden">
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800">
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">{icon}{title}</h3>
                  <div className="flex gap-2">
                    <button onClick={() => copySection(content, key)}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-slate-700 text-slate-400 hover:text-white hover:border-slate-600 transition-all">
                      {copied === key ? <><Check size={13} className="text-green-400" /> Copied</> : <><Copy size={13} /> Copy</>}
                    </button>
                    <button onClick={() => generatePDF(formData, { [key]: content })}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-amber-500/30 text-amber-400 hover:bg-amber-500/10 transition-all">
                      <FileText size={13} /> Export
                    </button>
                  </div>
                </div>
                <div className="p-6">
                  <article className="prose prose-invert prose-sm sm:prose-base prose-slate max-w-none text-slate-300">
                    <ReactMarkdown>{key === "budget" ? convertCurrency(content) : content}</ReactMarkdown>
                  </article>
                </div>
              </motion.div>
            ) : null)}

            {/* CTA */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Link href="/packages"
                className="flex items-center justify-center gap-2 rounded-xl bg-brand-600 hover:bg-brand-500 px-6 py-3.5 font-semibold text-white transition-all shadow-lg shadow-brand-600/20">
                <Sparkles size={18} /> Browse Matching Packages
              </Link>
              <button onClick={() => generatePDF(formData, results)}
                className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 px-6 py-3.5 font-semibold text-white transition-all shadow-lg shadow-amber-500/20">
                <Download size={18} /> Download Full Plan
              </button>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}
